### PR TITLE
Subreddit navigation

### PR DESCRIPTION
**Pull request by WoH**
Fixed:
- Typos
- Imports
Added:
- ignore yarn
- subreddit navigation
- Little bit of ES6
 
Some of these are just suggestions, feel free to modify as you please.

### CODE REVIEW

**Comment by smartapant** [comment]
Thanks! I will look through the changes tomorrow or on Monday. Could you please change target branch from 'master' to 'new-feats'?

**Comment by WoH** [comment]
Done :beers:

**Comment by smartapant** [comment]
I will merge and play with it a little :)

**Comment by WoH** [comment]
Just fixed the loadMore() to work within subreddits, I'll add another PR in a sec, beware :laughing:

**Comment by smartapant** [comment]
I'm going to the cinema so i'll check it later :)

**Pull request merged**
